GET http://localhost:3000/subscribers

###

Get http://localhost:3000/subscribers/5d3e0db7cb4be0bfc4c25ff9

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "name": "Lizzy",
  "subscribedChannel": "Bennetts Channel"
}

###
DELETE http://localhost:3000/subscribers/5d3e0db7cb4be0bfc4c25ff9

###
PATCH http://localhost:3000/subscribers/5d3e144ecb4be0bfc4c25ffa
Content-Type: application/json 

{
  "name": "Tommy"
}