GET http://localhost:3005/subscribers

###

Get http://localhost:3005/subscribers/5d34bb8c457d3b59d3c8b850

###

POST http://localhost:3005/subscribers
Content-Type: application/json

{
  "name": "rob",
  "subscribedChannel": "bobs channel"
}

###
DELETE http://localhost:3005/subscribers/5d34bb8c457d3b59d3c8b850

###
PATCH http://localhost:3005/subscribers/5d308991b877721cda23eb0f
Content-Type: application/json 

{
  "name": "Titty Tom"
}